project:
  type: website
  render:
    - "*.qmd"
    - "!code/"
    - "!slides/"
website:
  title: "EDS214 - Analytical Workflows and Scientific Reproducibility"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Daily Materials"
        menu:
          - text: "Day 1: Reproducible & collaborative workflows"
            href: day_1.html
          - text: "Day 2: Working on a remote server"
            href: day_2.html
          - text: "Day 3: Getting data in a programmatic way"
            href: day_3.html
          - text: "Day 4: Being reproducible: Tools and Practices"
            href: day_4.html
          - text: "Day 5: Reproducible for all"
            href: day_5.html
          - text: "Group project"
            href: group_project.html
      - text: "Resources"
        href: resources.html
    tools:
      - icon: github
        href: https://github.com/brunj7/EDS-214-analytical-workflows

format:
  html:
    theme: 
      - cosmo
      - medsstyles.scss
    toc: true
    include-after-body: _footer.html



